2nd js project
S-BLH/S-BLH-roman-numeral-converter pull request #1
Opened 2024-06-26 09:32 UTC by S-BLH

2024-06-26 10:16 UTC, latifa-wakili commented
good job !
you created a complate repository
your code are clean
no errors
great arranged branchs

2024-06-27 15:59 UTC, ahzamir commented
@S-BLH 

- I can see you pushed lots of codes in just a few commits, which is wrong.
- At least have some 5-6 more commits so I can review your project.
  - [SUGESSION] - You can add some more design to your code and commit it.

2024-06-29 10:03 UTC, S-BLH commented
@ahzamir as you said I added design to my project, kindly review it.

2024-06-29 17:32 UTC, ahzamir requested changes
@S-BLH 

- Well done you have implemented some of the requirements but still your project needs some changes please check the comments below for more details:

2024-06-29 17:32 UTC, ahzamir commented on index.html
> +  </style>
- You need to have your CSS code in a separate file like `styles.css` and add its link using `<link>` tag inside your `<head>` tag in your HTML file.

2024-06-29 17:32 UTC, ahzamir commented on index.html
> +  </script>
- You need to have your JS code in a separate file like `script.js` and add its link using `<script>` tag at the end of your <body>` in your HTML file.

2024-06-29 17:32 UTC, ahzamir commented on README.md
> +MIT license.
- Add a demo section with a screenshot of your project and also add How to use section to your README.md file

2024-06-30 10:28 UTC, S-BLH commented
@ahzamir ostad I solved the probs, please review it.

2024-07-01 07:15 UTC, ahzamir commented
@S-BLH 

- Your demo image is not showing in your README file
  - Inorder to add the screenshot to your readme you have to option:
    - You can add the screenshot to your project folder and linked it.
    - You can drag and drop it directly yo your readme in githib.

2024-07-01 10:01 UTC, S-BLH commented
@ahzamir please kindly, re-review my project, as I modified the errors

2024-07-02 10:54 UTC, ahzamir requested changes
@S-BLH 

- Still your README.md file is not clean please don't submit with the same mistake again and again and don't make changes to your development branch as it will create conflicts.

2024-07-02 10:54 UTC, ahzamir commented on README.md
> +<<<<<<< HEAD
- Remove this

2024-07-02 10:54 UTC, ahzamir commented on README.md
> +![Demo]:C:\Users\Black Store\Desktop\Screenshot 2024-06-30 144151.png
- Here, it is not showing the screenshot, I told you not to use image link from your Disk C or ... instead, add the screenshot to your project folder and then use its link like this `FILE_NAME.FILE_FORMAT` for example `image.png`

2024-07-02 10:54 UTC, ahzamir commented on README.md
> +live link of the project:https://s-blh.github.io/S-BLH-roman-numeral-converter/
Change this like this:
- Just copy and paste this
```
[live link of the project](https://s-blh.github.io/S-BLH-roman-numeral-converter/)
```

2024-07-02 11:25 UTC, S-BLH commented
@ahzamir sorry ostad I didnt know that the screen shot  linkdidnt work, please review it.

2024-07-04 00:54 UTC, ahzamir requested changes
@S-BLH 

- Still got the same issue with the screenshot

2024-07-04 00:54 UTC, ahzamir commented on README.md
> +![Demo]:![alt text](<Screenshot 2024-06-30 144151-1.png>)
- I can not see your screenshot in your project folder and also you used here wrong use it like this:
- First, add your screenshot to your project folder
- Then just copy and paste this and add the name of your screenshot:
```
![Image](HERE_REMOVE THE TEXT AND ADD YOUR OWN IMAGE NAME AND FORMAT EXAMPLE screenshot.png)
```

2024-07-04 16:14 UTC, ahzamir approved these changes
### Hi @S-BLH 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
![image](https://github.com/S-BLH/S-BLH-roman-numeral-converter/assets/96838030/27251d49-5e3a-4eef-a5c9-53859ed4a578)

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![WinkThumbsUpGIF](https://github.com/ZohalMirkhel/palindrome/assets/96838030/e5ee293e-072a-4806-bde0-b64e13140efa)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Roman Numeral Converter project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️Your repo have been reviewed by your partner
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-07-08 07:46 UTC, merged